# permissions for end users to edit corepodpermissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: corepodpermission-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testcrd
    app.kubernetes.io/part-of: testcrd
    app.kubernetes.io/managed-by: kustomize
  name: corepodpermission-editor-role
rules:
- apiGroups:
  - webapp.dev.cloud
  resources:
  - corepodpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.dev.cloud
  resources:
  - corepodpermissions/status
  verbs:
  - get
