# permissions for end users to view testpvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testpvc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testcrd
    app.kubernetes.io/part-of: testcrd
    app.kubernetes.io/managed-by: kustomize
  name: testpvc-viewer-role
rules:
- apiGroups:
  - webapp.dev.cloud
  resources:
  - testpvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.dev.cloud
  resources:
  - testpvcs/status
  verbs:
  - get
